/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // -- Severity palette (ONLY for risk/priority/status) --
        "severity-red": "#DC2626",
        "severity-orange": "#EA580C",
        "severity-amber": "#D97706",
        "severity-green": "#16A34A",

        // -- Phase 2B backgrounds --
        "phase-bg": "#0B0E14",
        "phase-elevated": "#12151C",
        "phase-card": "#1A1E28",

        // -- Phase 2B text --
        "phase-text": "#E8EAED",
        "phase-text-secondary": "#9CA3AF",

        // -- Surface / neutral system --
        "on-surface": "#e5e2e1",
        "secondary-fixed-dim": "#c6c6cf",
        "surface-tint": "#c6c6c7",
        "surface-container": "#201f1f",
        "error-container": "#93000a",
        "on-secondary-container": "#b4b4bd",
        "primary-fixed-dim": "#c6c6c7",
        "on-primary-container": "#636565",
        "tertiary-fixed": "#e2e2e2",
        "surface-variant": "#353434",
        "on-primary-fixed": "#1a1c1c",
        "on-error-container": "#ffdad6",
        "background": "#141313",
        "surface-container-highest": "#353434",
        "on-secondary-fixed": "#1a1b22",
        "secondary-container": "#45464e",
        "surface": "#141313",
        "secondary-fixed": "#e2e1eb",
        "primary-fixed": "#e2e2e2",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary-fixed-variant": "#454747",
        "primary": "#ffffff",
        "surface-raised": "#171717",
        "on-secondary": "#2f3037",
        "primary-container": "#e2e2e2",
        "on-tertiary-fixed": "#1a1c1c",
        "tertiary-container": "#e2e2e2",
        "outline": "#8e9192",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-background": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "tertiary": "#ffffff",
        "on-error": "#690005",
        "on-tertiary-container": "#636565",
        "outline-variant": "#444748",
        "on-surface-variant": "#c4c7c8",
        "inverse-surface": "#e5e2e1",
        "surface-base": "#0a0a0a",
        "surface-container-high": "#2a2a2a",
        "secondary": "#c6c6cf",
        "on-secondary-fixed-variant": "#45464e",
        "surface-bright": "#3a3939",
        "surface-container-low": "#1c1b1b",
        "on-tertiary": "#2f3131",
        "on-primary": "#2f3131",
        "surface-lowest": "#000000",
        "surface-container-lowest": "#0e0e0e",
        "surface-dim": "#141313",
        "inverse-primary": "#5d5f5f",
        "border-subtle": "#262626",
      },
      borderRadius: {
        DEFAULT: "2px",
        lg: "4px",
        xl: "6px",
        full: "4px",
      },
      spacing: {
        "stack-sm": "8px",
        gutter: "16px",
        "stack-lg": "32px",
        "space-unit": "4px",
        "stack-md": "16px",
        "margin-page": "24px",
      },
      fontFamily: {
        "headline-lg": ["Geist"],
        "display-lg": ["Geist"],
        "headline-md": ["Geist"],
        "label-sm": ["JetBrains Mono"],
        "body-lg": ["Geist"],
        "body-md": ["Geist"],
        "label-md": ["JetBrains Mono"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
