import Icon from "../components/ui/Icon.jsx";

export default function HelpPage() {
  return (
    <main className="flex-1 overflow-y-auto bg-phase-bg p-6">
      <div className="max-w-[800px] mx-auto">
        <div className="flex items-end justify-between border-b border-[#1E2330] pb-3 mb-6">
          <div>
            <h2 className="text-[20px] font-semibold text-phase-text">Help</h2>
            <p className="text-[13px] text-phase-text-secondary mt-1">
              VYOMA GIS Operational Suite — user guide
            </p>
          </div>
        </div>

        <div className="space-y-6">
          {/* About */}
          <div className="bg-phase-elevated rounded-[4px] border border-[#1E2330] p-5">
            <h3 className="text-[14px] font-semibold text-phase-text mb-3 flex items-center gap-2">
              <Icon name="info" className="text-[16px] text-phase-text-secondary" />
              About VYOMA
            </h3>
            <p className="text-[13px] text-phase-text-secondary leading-relaxed">
              VYOMA (Village Yield Optimization & Migration Analyst) is a GIS-based
              disaster relocation decision-support tool developed for the National
              Disaster Response Force (NDRF) and district administration officials
              under the Ministry of Home Affairs. Built for Smart India Hackathon 2026.
            </p>
          </div>

          {/* Data Model */}
          <div className="bg-phase-elevated rounded-[4px] border border-[#1E2330] p-5">
            <h3 className="text-[14px] font-semibold text-phase-text mb-3 flex items-center gap-2">
              <Icon name="psychology" className="text-[16px] text-phase-text-secondary" />
              Underlying Model
            </h3>
            <p className="text-[13px] text-phase-text-secondary leading-relaxed mb-3">
              Risk assessments are generated by an XGBoost village-level classifier
              covering ~44,000 villages across 7 North-Eastern Indian states. Each
              village receives a continuous risk score (0.0–1.0), a risk level
              (RED/ORANGE/GREEN), and a relocation priority tier.
            </p>
            <div className="grid grid-cols-3 gap-3 mt-4">
              <div className="bg-phase-card rounded-[4px] border border-[#1E2330] p-3 text-center">
                <span className="text-[10px] text-phase-text-secondary uppercase tracking-wider font-mono block mb-1">Risk Score</span>
                <span className="text-[16px] font-mono font-bold text-phase-text">0.0 – 1.0</span>
              </div>
              <div className="bg-phase-card rounded-[4px] border border-[#1E2330] p-3 text-center">
                <span className="text-[10px] text-phase-text-secondary uppercase tracking-wider font-mono block mb-1">Risk Levels</span>
                <span className="text-[16px] font-mono font-bold text-phase-text">3 tiers</span>
              </div>
              <div className="bg-phase-card rounded-[4px] border border-[#1E2330] p-3 text-center">
                <span className="text-[10px] text-phase-text-secondary uppercase tracking-wider font-mono block mb-1">Priority</span>
                <span className="text-[16px] font-mono font-bold text-phase-text">4 tiers</span>
              </div>
            </div>
          </div>

          {/* Navigation Guide */}
          <div className="bg-phase-elevated rounded-[4px] border border-[#1E2330] p-5">
            <h3 className="text-[14px] font-semibold text-phase-text mb-3 flex items-center gap-2">
              <Icon name="menu_book" className="text-[16px] text-phase-text-secondary" />
              Navigation Guide
            </h3>
            <div className="space-y-3">
              {[
                { icon: "dashboard", label: "Dashboard", desc: "District-level overview with key metrics, map, and critical villages" },
                { icon: "map", label: "Hazard Map", desc: "Interactive GIS map with risk-colored village markers and clustering" },
                { icon: "home_pin", label: "Villages", desc: "Sortable/filterable table of all villages with risk profiles" },
                { icon: "priority_high", label: "Relocation Priority", desc: "Kanban board organizing villages by relocation urgency" },
                { icon: "location_on", label: "Relocation Sites", desc: "Registered relocation sites with capacity and infrastructure status" },
                { icon: "analytics", label: "Analytics", desc: "Risk distribution charts, capacity trends, and SHAP factor analysis" },
              ].map((item) => (
                <div key={item.label} className="flex items-start gap-3">
                  <Icon name={item.icon} className="text-[18px] text-phase-text-secondary mt-0.5 shrink-0" />
                  <div>
                    <span className="text-[13px] text-phase-text font-medium">{item.label}</span>
                    <p className="text-[12px] text-phase-text-secondary">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Keyboard Shortcuts */}
          <div className="bg-phase-elevated rounded-[4px] border border-[#1E2330] p-5">
            <h3 className="text-[14px] font-semibold text-phase-text mb-3 flex items-center gap-2">
              <Icon name="keyboard" className="text-[16px] text-phase-text-secondary" />
              Keyboard Shortcuts
            </h3>
            <div className="space-y-2">
              {[
                { keys: "Scroll", action: "Zoom in/out on map" },
                { keys: "Click + Drag", action: "Pan map" },
                { keys: "Click marker", action: "Open village popup" },
              ].map((shortcut) => (
                <div key={shortcut.keys} className="flex items-center justify-between">
                  <span className="text-[12px] font-mono text-phase-text-secondary px-2 py-0.5 bg-phase-card rounded-[2px] border border-[#1E2330]">
                    {shortcut.keys}
                  </span>
                  <span className="text-[12px] text-phase-text-secondary">{shortcut.action}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
